In [1]:
import pandas as pd

# Charts for report

A notebook to produce charts for the final report. The charts themselves are made using [Flourish](https://flourish.social/).

Fetch the data needed

In [2]:
charities = pd.read_csv("../data/charities_active.csv", index_col="org_id")
ukcat = pd.read_csv("../data/charities_active-ukcat.csv")
cics_ukcat = pd.read_csv("../data/cics-ukcat.csv")

C:\Users\drkan\AppData\Local\Temp\ipykernel_9052\4149517210.py:1: DtypeWarning: Columns (1,8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  charities = pd.read_csv("../data/charities_active.csv", index_col="org_id")

In [3]:
ukcat_labels = pd.read_csv("../data/ukcat.csv", index_col="Code")
ukcat_labels

,tag,Category,Subcategory,Level,Notes,Related ICNPTSO code,Regular expression,Exclude regular expression
Code,,,,,,,,
AN,Animals,Animals,NaN,1,Includes animals without their own category. I...,E21;E20,\b(animals?|cats?|rabbits?|cows?|sheep|pigs?|c...,NaN
AN101,Cats,Animals,NaN,3,NaN,NaN,\b(cats?|felines?)\b,NaN
AN102,Dogs,Animals,NaN,3,NaN,NaN,\b(dogs?|canines?|kennels?|Rhodesian Ridgeback)\b,NaN
AN103,Donkeys,Animals,NaN,3,NaN,E21;E29;E20,\b(donkey|donkeys|mule(s)?)\b,NaN
AN104,Horses,Animals,NaN,3,NaN,E21;E29;E20,\b(horses?|equine|dressage|(pon(y|ies)+)|horse...,NaN
...,...,...,...,...,...,...,...,...
SO103,Democracy,Society,NaN,3,NaN,G11,\b(democrac(tic|y)|political engagement)\b,NaN
SO104,Equality and diversity,Society,NaN,3,NaN,G11,\b(equality and diversity|(sexual|racial|gende...,NaN
SO105,Human rights,Society,NaN,3,NaN,G11,\b((human|civil|constitutional|civic|natural|u...,NaN
SO106,Racial justice,Society,NaN,3,NaN,G11,\b(bigotry|racis(t|m)|racialism|racial hate cr...,NaN
SO107,Religious; racial or cross-border harmony,Society,NaN,3,Includes interface areas,G11,\b(cross-cultural|(ethnic|racial|religious|cro...,NaN

## Number of tags per charity

In [4]:
ukcat.groupby("org_id").size().rename("number_of_tags")

org_id
GB-CHC-1000000     2
GB-CHC-1000001     1
GB-CHC-1000003     2
GB-CHC-1000005     2
GB-CHC-1000007     4
                  ..
GB-SC-SC055276     6
GB-SC-SC055277     6
GB-SC-SC055278     5
GB-SC-SC055279     4
GB-SC-SC055280    10
Name: number_of_tags, Length: 196182, dtype: int64

In [5]:
charities = charities.join(ukcat.groupby("org_id").size().rename("number_of_tags"))
charities.loc[:, "number_of_tags"] = charities["number_of_tags"].fillna(0)

In [7]:
# cics = cics.join(ukcat.groupby("org_id").size().rename("number_of_tags"))
# charities.loc[:, "number_of_tags"] = charities["number_of_tags"].fillna(0)
cics_ukcat.groupby("org_id").size().rename("number_of_tags")

org_id
GB-CHC-1000003    2
GB-CHC-1000116    5
GB-CHC-1000389    1
GB-CHC-1000412    3
GB-CHC-1000430    1
                 ..
GB-SC-SC050247    2
GB-SC-SC050328    1
GB-SC-SC050384    1
GB-SC-SC050441    1
GB-SC-SC050464    3
Name: number_of_tags, Length: 65773, dtype: int64

In [8]:
n_tags = charities["number_of_tags"].astype(int).value_counts().sort_index()
cutoff = n_tags.index >= 15
over_cutoff = n_tags[cutoff].sum()
n_tags = n_tags[~cutoff]
n_tags.index = n_tags.index.astype(str).rename("Number of tags")
n_tags["15 or over"] = over_cutoff
n_tags = n_tags.rename("Number of charities").to_frame()
n_tags.loc[:, "% of charities"] = (
    n_tags["Number of charities"].divide(n_tags["Number of charities"].sum()).multiply(100).round(1)
)
n_tags

                Number of charities  % of charities
Number of tags
0                              7732             3.8
1                             21500            10.6
2                             33175            16.3
3                             37364            18.4
4                             32241            15.9
5                             23598            11.6
6                             17634             8.7
7                             11267             5.5
8                              7082             3.5
9                              4199             2.1
10                             2541             1.2
11                             1563             0.8
12                             1003             0.5
13                              701             0.3
14                              464             0.2
15 or over                     1253             0.6

## Number of charities with 0 tags, by whether grantmaking is their main activity

In [9]:
charities.loc[charities["number_of_tags"] == 0, "grant_making_is_main_activity"].value_counts()

grant_making_is_main_activity
False    5149
True     1545
Name: count, dtype: int64

## Number of charities per tag category (direct and indirect)

In [10]:
ukcat.loc[:, "method"] = "direct"

In [12]:
extra = ukcat[ukcat["ukcat_code"].apply(len) > 2]
extra.loc[:, "ukcat_code"] = extra["ukcat_code"].str[0:2]
extra.loc[:, "method"] = "indirect"
all_ukcat = pd.concat([ukcat, extra], ignore_index=True).drop_duplicates(["org_id", "ukcat_code"])
all_ukcat

                 org_id ukcat_code    method
0        GB-CHC-1000000         ED    direct
1        GB-CHC-1000000      ED102    direct
2        GB-CHC-1000001         AR    direct
3        GB-CHC-1000003      CA103    direct
4        GB-CHC-1000003      ED101    direct
...                 ...        ...       ...
1468367  GB-SC-SC055280         AS  indirect
1468368  GB-SC-SC055280         BE  indirect
1468370  GB-SC-SC055280         EC  indirect
1468371  GB-SC-SC055280         SL  indirect
1468372  GB-SC-SC055280         SW  indirect

[1205401 rows x 3 columns]

In [13]:
charities_per_tag = (
    pd.crosstab(
        all_ukcat.join(ukcat_labels, on="ukcat_code").loc[all_ukcat["ukcat_code"].apply(len) == 2, "tag"],
        all_ukcat.loc[all_ukcat["ukcat_code"].apply(len) == 2, "method"],
        margins="column",
        margins_name="Total",
    )
    .drop("Total")
    .sort_values("Total", ascending=False)
)
charities_per_tag

method                              direct  indirect  Total
tag
Education                            56065     27682  83747
Beneficiary group                        0     77759  77759
Associations                         27695     18385  46080
Religion                             17347     28582  45929
Social welfare                          54     38996  39050
Charity and VCS support              13929     19599  33528
Leisure                                  2     30300  30302
Health                               18331     11865  30196
Arts                                 11995     17663  29658
Charitable activities                   40     29555  29595
Facilities                              24     19529  19553
Economic and community development       0     16061  16061
Heritage                              6024      7513  13537
Housing                               3665      9480  13145
Research                              7160      3892  11052
Childcare                             1252      7726   8978
Society                                745      7192   7937
Animals                               4254       131   4385
Environment                              0      3872   3872
Saving of lives                        629      3070   3699
Social care                            466      3165   3631
Armed forces                          1675       718   2393
Crime and Justice                      737      1140   1877
Professions                             15      1286   1301

In [14]:
charities_per_tag.divide(len(charities)).multiply(100).round(1)

method                              direct  indirect  Total
tag
Education                             27.6      13.6   41.2
Beneficiary group                      0.0      38.2   38.2
Associations                          13.6       9.0   22.7
Religion                               8.5      14.1   22.6
Social welfare                         0.0      19.2   19.2
Charity and VCS support                6.9       9.6   16.5
Leisure                                0.0      14.9   14.9
Health                                 9.0       5.8   14.9
Arts                                   5.9       8.7   14.6
Charitable activities                  0.0      14.5   14.6
Facilities                             0.0       9.6    9.6
Economic and community development     0.0       7.9    7.9
Heritage                               3.0       3.7    6.7
Housing                                1.8       4.7    6.5
Research                               3.5       1.9    5.4
Childcare                              0.6       3.8    4.4
Society                                0.4       3.5    3.9
Animals                                2.1       0.1    2.2
Environment                            0.0       1.9    1.9
Saving of lives                        0.3       1.5    1.8
Social care                            0.2       1.6    1.8
Armed forces                           0.8       0.4    1.2
Crime and Justice                      0.4       0.6    0.9
Professions                            0.0       0.6    0.6

## Table used to create appendix A

In [15]:
ukcat_labels.join(ukcat["ukcat_code"].value_counts().rename("Matched charities").astype(int)).reset_index()[
    [
        "Category",
        "Subcategory",
        "tag",
        "Code",
        "Matched charities",
    ]
].rename(columns={"tag": "Tag"}).to_csv("../data/ukcat_for_report.csv", index=False)

In [36]:
summary = ukcat.join(
    charities[["income", "spending"]], on="org_id"
).groupby("ukcat_code").agg(**{
    "Charities": ("org_id", "nunique"),
    "Income": ("income", "sum"),
    "Spending": ("spending", "sum"),
}).join(
    cics_ukcat.groupby("ukcat_code").size().rename("Community Interest Companies"), how="outer"
).join(
    ukcat_labels
).assign(**{
    "Subcategory": lambda x: x["Subcategory"].fillna(x["tag"]),
})[["Category", "Subcategory", "tag", "Charities", "Income", "Spending", "Community Interest Companies"]]
summary.to_csv("../data/ukcat_summary.csv")
summary.to_clipboard()
summary

,Category,Subcategory,tag,Charities,Income,Spending,Community Interest Companies
ukcat_code,,,,,,,
AF,Armed forces,Armed forces,Armed forces,1675,1.334056e+09,1.318779e+09,646
AF101,Armed forces,Army,Army,559,4.297630e+08,2.458054e+08,134
AF102,Armed forces,Navy,Navy,507,1.942878e+08,2.097779e+08,40
AF103,Armed forces,RAF,RAF,361,1.975720e+08,1.954064e+08,39
AF104,Armed forces,Veterans,Veterans,320,3.750847e+08,4.114350e+08,163
...,...,...,...,...,...,...,...
SW202,Social welfare,Abuse,Domestic abuse,727,1.326359e+09,1.314319e+09,1846
SW203,Social welfare,Abuse,Refuge or shelter,279,2.590455e+08,2.488192e+08,208
SW204,Social welfare,Abuse,Sexual abuse,312,9.657894e+08,9.233862e+08,429
SW300,Social welfare,Food,Food,6449,2.386814e+09,2.304349e+09,7332
SW301,Social welfare,Food,Food banks,1475,6.788907e+08,6.589798e+08,1245

In [ ]:
ukcat_labels.join(ukcat["ukcat_code"].value_counts().rename("Charities").astype(int)).reset_index()[
    [
        "Category",
        "Subcategory",
        "tag",
        "Code",
        "Matched charities",
    ]
].rename(columns={"tag": "Tag"})

,Category,Subcategory,Tag,Code,Matched charities
0,Animals,NaN,Animals,AN,4254.0
1,Animals,NaN,Cats,AN101,456.0
2,Animals,NaN,Dogs,AN102,949.0
3,Animals,NaN,Donkeys,AN103,59.0
4,Animals,NaN,Horses,AN104,610.0
...,...,...,...,...,...
249,Society,NaN,Democracy,SO103,72.0
250,Society,NaN,Equality and diversity,SO104,1564.0
251,Society,NaN,Human rights,SO105,1001.0
252,Society,NaN,Racial justice,SO106,130.0
253,Society,NaN,Religious; racial or cross-border harmony,SO107,1095.0